# Generated by Django 4.2 on 2023-05-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmrs_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agmdevice',
            old_name='loacation',
            new_name='location',
        ),
    ]
