# Generated by Django 4.2 on 2023-05-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmrs_app', '0004_telidosidevice_date_time_alter_telidosidevice_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agmdevice',
            name='device_type',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=10),
        ),
    ]
