# Generated by Django 4.2 on 2023-05-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmrs_app', '0005_agmdevice_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agmdevice',
            name='device_type',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=10),
        ),
    ]
