# Generated by Django 4.2 on 2023-05-10 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agmrs_app', '0006_alter_agmdevice_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agmdevice',
            name='average_value',
        ),
        migrations.RemoveField(
            model_name='agmdevice',
            name='battery_percentage',
        ),
        migrations.RemoveField(
            model_name='agmdevice',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='agmdevice',
            name='location',
        ),
        migrations.RemoveField(
            model_name='agmdevice',
            name='present_value',
        ),
        migrations.RemoveField(
            model_name='agmdevice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='telidosidevice',
            name='count',
        ),
        migrations.RemoveField(
            model_name='telidosidevice',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='telidosidevice',
            name='total_dose',
        ),
        migrations.AlterField(
            model_name='agmdevice',
            name='device_type',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=10),
        ),
        migrations.CreateModel(
            name='TelidosiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dose', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agmrs_app.telidosidevice')),
            ],
        ),
        migrations.CreateModel(
            name='AgmDeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('present_value', models.FloatField()),
                ('average_value', models.FloatField(default=0)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('battery_percentage', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('alarm', 'Alarm'), ('normal', 'Normal')], max_length=10)),
                ('device_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agmrs_app.agmdevice')),
            ],
        ),
    ]
