# Generated by Django 4.2 on 2023-05-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmrs_app', '0007_remove_agmdevice_average_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agmdevicedata',
            name='device_type',
        ),
        migrations.AlterField(
            model_name='agmdevice',
            name='device_type',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=10),
        ),
    ]
